version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    ports:
      - 172.17.0.1:35574:80
      - 172.17.0.1:3012:3012
    volumes:
      - ./data:/data
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - WEB_VAULT_ENABLED=true
      - SHOW_PASSWORD_HINT=false
      - INVITATIONS_ALLOWED=false
      
  
